# Generated by Django 3.0.7 on 2021-05-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='is_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='show_in_feed',
            field=models.BooleanField(default=True),
        ),
    ]
