# Generated by Django 3.0.7 on 2021-06-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210522_1200'),
        ('blogs', '0002_auto_20210601_1040'),
    ]

    operations = [
    ]
