# Generated by Django 3.0.7 on 2021-06-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_merge_20210601_1043'),
        ('blogs', '0003_upvote'),
    ]

    operations = [
    ]
