# Generated by Django 3.0.7 on 2021-06-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_upvote'),
        ('blogs', '0004_post_tags'),
    ]

    operations = [
    ]
